substitutions:
  id: air-sensor
  device_name: DIY Air Sensor

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/wemos-d1-mini32.yaml
<<: !include common/common-esp32.yaml

uart:
  rx_pin: 16
  tx_pin: 17
  baud_rate: 9600

i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

sensor:
  - platform: senseair
    co2:
      name: $device_name CO₂
    update_interval: 30s
  - platform: sht3xd
    i2c_id: bus_a
    address: 0x44
    update_interval: 10s
    temperature:
      name: $device_name Temperature
    humidity:
      name: $device_name Humidity
