esphome:
  name: air-conditioner-remote

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

climate:
  - platform: tcl112
    name: "Indoor AC"
    visual:
      min_temperature: 18
      max_temperature: 28
      temperature_step: 1
