esphome:
  name: air-sensor

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home.arpa

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

uart:
  rx_pin: 16
  tx_pin: 17
  baud_rate: 9600

i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

sensor:
  - platform: senseair
    co2:
      name: CO₂
    update_interval: 30s
  - platform: sht3xd
    i2c_id: bus_a
    address: 0x44
    update_interval: 10s
    temperature:
      name: Temperature
    humidity:
      name: Humidity
