substitutions:
  id: air-conditioner-remote
  device_name: Air Conditioner Remote

esphome:
  name: air-conditioner-remote

esp32:
  board: wemos_d1_mini32

<<: !include common/common_esp32.yaml

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

climate:
  - platform: tcl112
    name: $device_name Indoor AC
    visual:
      min_temperature: 18
      max_temperature: 28
      temperature_step: 1
