substitutions:
  id: atlas-sensor
  device_name: Atlas Sensor

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/espressif-esp32h2.yaml
<<: !include common/common-esp32-thread.yaml

button:
  - platform: restart
    name: "$device_name Restart"

switch:
  - platform: gpio
    internal: True
    pin: GPIO14
    name: "$device_name pH On"
    inverted: no
  - platform: gpio
    internal: True
    pin: GPIO11
    name: "$device_name RTD Temp On"
    inverted: yes
  - platform: gpio
    internal: True
    pin: GPIO13
    name: "$device_name EC On"
    inverted: no
  - platform: gpio
    internal: True
    pin: GPIO12
    name: "$device_name AUX On"
    inverted: no

i2c:
  sda: GPIO22
  scl: GPIO10
  scan: True

sensor:
  - platform: ezo
    id: ph_ezo
    name: "$device_name pH"
    address: 99
    accuracy_decimals: 2
    unit_of_measurement: "pH"
    update_interval: 10s
  - platform: ezo
    id: ec_ezo
    name: "$device_name EC"
    address: 100
    accuracy_decimals: 0
    unit_of_measurement: "PPM"
    update_interval: 10s
  - platform: ezo
    id: rtd_ezo
    name: "$device_name RTD Temp"
    address: 102
    accuracy_decimals: 2
    unit_of_measurement: "°C"
    update_interval: 60s
