substitutions:
  id: atlas-sensor
  device_name: Atlas Sensor

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/espressif-esp32c5.yaml
<<: !include common/common-esp32.yaml

button:
  - platform: restart
    name: "$device_name Restart"

switch:
  - platform: gpio
    internal: True
    pin: GPIO3
    name: "$device_name pH Enable"
    inverted: no
  - platform: gpio
    internal: True
    pin: GPIO6
    name: "$device_name RTD Temp Enable"
    inverted: yes
  - platform: gpio
    internal: True
    pin: GPIO4
    name: "$device_name EC Enable"
    inverted: no
  - platform: gpio
    internal: True
    pin: GPIO5
    name: "$device_name AUX Enable"
    inverted: no

i2c:
  sda: GPIO27
  scl: GPIO26
  scan: True

sensor:
  - platform: ezo
    id: ph_ezo
    name: "$device_name pH"
    address: 99
    accuracy_decimals: 2
    unit_of_measurement: "pH"
    update_interval: 10s
  - platform: ezo
    id: ec_ezo
    name: "$device_name EC"
    address: 100
    accuracy_decimals: 0
    unit_of_measurement: "PPM"
    update_interval: 10s
  - platform: ezo
    id: rtd_ezo
    name: "$device_name RTD Temp"
    address: 102
    accuracy_decimals: 2
    unit_of_measurement: "°C"
    update_interval: 60s
