substitutions:
  friendly_name: "Atlas Sensor"
  id: atlas-sensor

esphome:
  name: $id

esp8266:
  board: huzzah

<<: !include common/common_hotspot.yaml

switch:
  - platform: restart
    name: "$friendly_name Restart"
  - platform: gpio
    internal: True
    pin: GPIO14
    name: "$friendly_name pH On"
    inverted: no
  - platform: gpio
    internal: True
    pin: GPIO15
    name: "$friendly_name RTD Temp On"
    inverted: yes
  - platform: gpio
    internal: True
    pin: GPIO12
    name: "$friendly_name EC On"
    inverted: no

i2c:
  sda: GPIO04
  scl: GPIO05
  scan: True

sensor:
  - platform: ezo
    id: ph_ezo
    name: "$friendly_name pH"
    address: 99
    accuracy_decimals: 2
    unit_of_measurement: "pH"
    update_interval: 10s
  - platform: ezo
    id: ec_ezo
    name: "$friendly_name EC"
    address: 100
    accuracy_decimals: 0
    unit_of_measurement: "PPM"
    update_interval: 10s
  - platform: ezo
    id: rtd_ezo
    name: "$friendly_name RTD Temp"
    address: 102
    accuracy_decimals: 2
    unit_of_measurement: "°C"
    update_interval: 60s
