substitutions:
  devicename: "Atlas Sensor"

esphome:
  name: atlas-sensor

esp8266:
  board: huzzah

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: "ih92bjvtYt6r"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

switch:
  - platform: restart
    name: "${devicename} Restart"
  - platform: gpio
    internal: True
    pin: GPIO14
    name: "${devicename} pH On"
    inverted: no
  - platform: gpio
    internal: True
    pin: GPIO15
    name: "${devicename} RTD Temp On"
    inverted: yes
  - platform: gpio
    internal: True
    pin: GPIO12
    name: "${devicename} EC On"
    inverted: no

i2c:
  sda: GPIO04
  scl: GPIO05
  scan: True

sensor:
  - platform: ezo
    id: ph_ezo
    name: "${devicename} pH"
    address: 99
    accuracy_decimals: 2
    unit_of_measurement: "pH"
    update_interval: 10s
  - platform: ezo
    id: ec_ezo
    name: "${devicename} EC"
    address: 100
    accuracy_decimals: 0
    unit_of_measurement: "PPM"
    update_interval: 10s
  - platform: ezo
    id: rtd_ezo
    name: "${devicename} RTD Temp"
    address: 102
    accuracy_decimals: 2
    unit_of_measurement: "°C"
    update_interval: 60s
