substitutions:
  id: bentobox
  device_name: BentoBox v2.0

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/wemos-d1-mini32.yaml
<<: !include common/common-esp32.yaml

output:
  - platform: ledc
    pin: GPIO25
    id: gpio_25
    frequency: 25000 Hz
  - platform: ledc
    pin: GPIO32
    id: gpio_32
    frequency: 25000 Hz

fan:
  - platform: speed
    output: gpio_25
    id: fan_1
    name: "BentoBox Fan 1"
    speed_count: 4
  - platform: speed
    output: gpio_32
    id: fan_2
    name: "BentoBox Fan 2"
    speed_count: 4
