substitutions:
  id: bentobox
  device_name: BentoBox v2.0

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/espressif-esp32c6.yaml
<<: !include common/common-esp32.yaml

output:
  - platform: ledc
    pin: GPIO3
    id: fans_pwm
    frequency: 25000 Hz

fan:
  - platform: speed
    output: fans_pwm
    id: fans
    name: "$device_name Fans"

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO15
    num_leds: 1
    rmt_channel: 0
    chipset: WS2812
    name: "$device_name Light"
    restore_mode: RESTORE_DEFAULT_OFF
