substitutions:
  id: bentobox
  device_name: BentoBox v2.0

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/wemos-d1-mini32.yaml
<<: !include common/common-esp32.yaml

output:
  - platform: ledc
    pin: GPIO32
    id: fans_pwm
    frequency: 25000 Hz

fan:
  - platform: speed
    output: fans_pwm
    id: fans
    name: "$device_name Fans"
