esphome:
  name: bowflex-hr-monitor

esp32:
  board: wemos_d1_mini32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home.arpa

logger:

api:

ota:
  password: !secret ota_password

esp32_ble_tracker:

ble_client:
  - id: heart_rate_monitor
    mac_address: C9:3E:F1:9B:E7:77

sensor:
  - name: Heart rate RSSI
    platform: ble_rssi
    mac_address: C9:3E:F1:9B:E7:77
  - id: heart_rate_measurement
    name: Heart rate
    icon: mdi:heart
    platform: ble_client
    type: characteristic
    ble_client_id: heart_rate_monitor
    unit_of_measurement: bpm
    service_uuid: 180D
    characteristic_uuid: 2A37
    notify: true
    lambda: |-
      uint16_t heart_rate_measurement = x[1];
      if (x[0] & 1) {
          heart_rate_measurement += (x[2] << 8);
      }
      return (float)heart_rate_measurement;
