substitutions:
  id: esp32-c3-12f
  device_name: ESP32-C3-12F

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/espressif-esp32c3.yaml
<<: !include common/common_esp32.yaml

# Enable ESPHome status output though D5 PCB LED
status_led:
  pin:
    number: GPIO9
    inverted: True
