substitutions:
  devicename: ESP32-C3-12F

esphome:
  name: esp32-c3-12f
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf
    platform_version: https://github.com/platformio/espressif32#develop
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      # Specific to Bluetooth usage
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Payload size fix - Extend Watchdog timeout, should be "pre-flashed"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up provisioning Wi-Fi credentials to the device over BLE
esp32_improv:
  authorizer: none

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# Enable ESPHome status output though D5 PCB LED
status_led:
  pin:
    number: GPIO9
    inverted: True
