esphome:
  name: lilygo-t-dongle-s3

esp32:
  board: esp32-s3-devkitc-1

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  id: my_ota
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up provisioning Wi-Fi credentials to the device over BLE
esp32_improv:
  authorizer: none

# SPI for Display
spi:
  clk_pin: GPIO05
  mosi_pin: GPIO03

display:
  - platform: st7735
    model: "INITR_MINI160X80"
    reset_pin: GPIO01
    cs_pin: GPIO04
    dc_pin: GPIO02
    rotation: 0
    device_width: 80
    device_height: 160
    col_start: 26
    row_start: 1
    eight_bit_color: true
    update_interval: 5s
    lambda: |-
      // Draw a circle in the middle of the display
      it.filled_circle(it.get_width() / 2, it.get_height() / 2, 20);
