substitutions:
  id: lilygo-t-dongle-s3
  device_name: LilyGo T-Dongle S3

esphome:
  name: $id
  friendly_name: $device_name
  platformio_options:
    board_build.flash_mode: dio

<<: !include common/board/espressif-esp32s3.yaml
<<: !include common/common_esp32.yaml

# SPI for Display
spi:
  clk_pin: GPIO05
  mosi_pin: GPIO03

display:
  - platform: st7735
    model: "INITR_MINI160X80"
    reset_pin: GPIO01
    cs_pin: GPIO04
    dc_pin: GPIO02
    rotation: 0
    device_width: 80
    device_height: 160
    col_start: 26
    row_start: 1
    eight_bit_color: true
    update_interval: 5s
    lambda: |-
      // Draw a circle in the middle of the display
      it.filled_circle(it.get_width() / 2, it.get_height() / 2, 20);
