external_components:
  - source:
      type: local
      path: components
    components: [openhaystack]

esphome:
  name: openhaystack-demo-s3
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Time component for openhaystack daily key rotation
time:
  - platform: sntp
    id: sntp_time
    timezone: "UTC"
    on_time:
      # Trigger key rotation at 04:00:00 UTC every day
      - seconds: 0
        minutes: 0
        hours: 4
        then:
          - lambda: |-
              id(openhaystack_tag).schedule_key_rotation();

openhaystack:
  id: openhaystack_tag
  master_private_key: !secret openhaystack_master_private_key
  master_symmetric_key: !secret openhaystack_master_symmetric_key
