substitutions:
  id: openhaystack-demo
  device_name: OpenHaystack Demo

external_components:
  - source:
      type: local
      path: components
    components: [openhaystack]

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/wemos-d1-mini32.yaml
<<: !include common/common_hotspot.yaml

openhaystack:
  key: !secret openhaystack_key
