substitutions:
  id: openhaystack-demo
  device_name: OpenHaystack Demo

external_components:
  - source:
      type: local
      path: components
    components: [openhaystack]

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/wemos-d1-mini32.yaml
<<: !include common/common-hotspot.yaml

openhaystack:
  master_private_key: !secret openhaystack_master_private_key
  master_symmetric_key: !secret openhaystack_master_symmetric_key
