substitutions:
  id: openhaystack-demo
  device_name: OpenHaystack Demo

external_components:
  - source:
      type: local
      path: components
    components: [openhaystack]

esphome:
  name: $id
  friendly_name: $device_name

esp32:
  board: wemos_d1_mini32

<<: !include common/common_hotspot.yaml

openhaystack:
  key: !secret openhaystack_key
