substitutions:
  device_name: Shelly Plus PM Mini
  device_id: 6055f99c3db0

esphome:
  name: shellypmmini-6055f99c3db0
  friendly_name: "${device_name} ${device_id}"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    advanced:
      ignore_efuse_mac_crc: false

<<: !include common/common_esp32.yaml

# Enable ESPHome status output though red LED
status_led:
  pin:
    number: GPIO0
    inverted: true

uart:
  id: uart_bus
  tx_pin: GPIO6
  rx_pin: GPIO7
  baud_rate: 9600
  stop_bits: 1

binary_sensor:
  - platform: gpio
    name: ${device_name} Button
    pin:
      number: GPIO1
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - logger.log: "Button pressed"

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${device_name} Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 11db

  - platform: bl0942
    uart_id: uart_bus
    voltage:
      name: ${device_name} Voltage
    current:
      name: ${device_name} Current
    power:
      name: ${device_name} Power
      accuracy_decimals: 2
    energy:
      name: ${device_name} Energy
      accuracy_decimals: 5
    frequency:
      name: ${device_name} Frequency
      accuracy_decimals: 2
    update_interval: 1s

# Enable time component to reset energy at midnight
time:
  - platform: sntp # could be platform: homeassistant
    timezone: America/Santiago
