external_components:
  source: github://SebastianBar/esphome@tuya-new
  components: [tuya_new]
  refresh: 60s

esphome:
  name: somela-black-glass-connect
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      # Specific to Bluetooth usage
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Payload size fix - Extend Watchdog timeout, should be "pre-flashed"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Sets up provisioning Wi-Fi credentials to the device over BLE
esp32_improv:
  authorizer: none

# Enable logging
logger:
  # level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# Enable ESPHome status output though TYJW2S PCB LED
status_led:
  pin:
    number: GPIO10

uart:
  rx_pin: GPIO4
  tx_pin: GPIO9
  baud_rate: 9600

# Register the Tuya MCU connection
tuya_new:

climate:
  - platform: tuya_new
    name: "Somela Black Glass Connect"
    switch_datapoint: 0
    #switch_datapoint: 6
    target_temperature_datapoint: 7
    current_temperature_datapoint: 10
    hysteresis: 1
    visual:
      min_temperature: 5
      max_temperature: 50
      temperature_step: 1
