substitutions:
  id: somela-black-glass-connect
  device_name: Somela Black Glass Connect

external_components:
  source: github://jesserockz/esphome@tuya-new
  components: [tuya_new]
  refresh: 1d

esphome:
  name: $id
  friendly_name: $device_name

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      # Enable WPA3 support
      CONFIG_WPA_SUITE_B_192: y
      # Specific to Bluetooth usage
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Payload size fix - Extend Watchdog timeout
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

<<: !include common/common_esp32.yaml

# Enable ESPHome status output though TYJW2S PCB LED
status_led:
  pin:
    number: GPIO10

uart:
  id: uart_0
  rx_pin: GPIO4
  tx_pin: GPIO9
  baud_rate: 9600

# Register the Tuya MCU connection
tuya_new:
  uart_id: uart_0

climate:
  - platform: tuya_new
    name: "$device_name Climate"
    switch_datapoint: 0
    #switch_datapoint: 6
    target_temperature_datapoint: 7
    current_temperature_datapoint: 10
    hysteresis: 1
    visual:
      min_temperature: 5
      max_temperature: 50
      temperature_step: 1
