substitutions:
  id: somela-black-glass-connect
  device_name: Somela Black Glass Connect

external_components:
  source: github://jesserockz/esphome@tuya-new
  components: [tuya_new]
  refresh: 1d

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/espressif-esp32c3.yaml
<<: !include common/common_esp32.yaml

# Enable ESPHome status output though TYJW2S PCB LED
status_led:
  pin:
    number: GPIO10

uart:
  id: uart_0
  rx_pin: GPIO4
  tx_pin: GPIO9
  baud_rate: 9600

# Register the Tuya MCU connection
tuya_new:
  uart_id: uart_0

climate:
  - platform: tuya_new
    name: "$device_name Climate"
    switch_datapoint: 0
    #switch_datapoint: 6
    target_temperature_datapoint: 7
    current_temperature_datapoint: 10
    hysteresis: 1
    visual:
      min_temperature: 5
      max_temperature: 50
      temperature_step: 1
