substitutions:
  id: sonoff-s26-8377100060
  device_name: Sonoff S26
  device_id: "8377100060"

esphome:
  name: $id
  friendly_name: $device_name $device_id

esp8266:
  board: esp8285

<<: !include common/common_hotspot.yaml

# Enable ESPHome status output though green LED
status_led:
  pin:
    number: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "$device_name $device_id Button"
    on_press:
      - switch.toggle: relay

sensor:
  - platform: wifi_signal
    name: "$device_name $device_id WiFi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    name: "$device_name $device_id Relay"
    pin: GPIO12
    id: relay
  - platform: restart
    name: "$device_name $device_id Restart"
