substitutions:
  devicename: Sonoff POWR2
  deviceserial: 00139037F2

esphome:
  name: sonoff-powr2-00139037f2

esp8266:
  board: esp8285

<<: !include common/wifi_failover_hotspot.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Enable ESPHome status output though green LED
status_led:
  pin:
    number: GPIO13
    inverted: True

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${devicename} ${deviceserial} Button
    internal: true
    on_press:
      - switch.toggle: relay

sensor:
  - platform: wifi_signal
    name: ${devicename} ${deviceserial} WiFi Signal
    update_interval: 60s
  - platform: cse7766
    update_interval: 1s
    current:
      name: ${devicename} ${deviceserial} Current
      accuracy_decimals: 5
    voltage:
      name: ${devicename} ${deviceserial} Voltage
    power:
      id: sonoff_power
      name: ${devicename} ${deviceserial} Power
      unit_of_measurement: W
      accuracy_decimals: 2
  - platform: template
    id: sonoff_power_kw
    update_interval: 1s
    name: ${devicename} ${deviceserial} Power (kW)
    unit_of_measurement: kW
    accuracy_decimals: 4
    state_class: measurement
    device_class: power
    lambda: 'return (id(sonoff_power).state / 1000);'
  - platform: total_daily_energy
    name: ${devicename} ${deviceserial} Total Daily Energy
    power_id: sonoff_power_kw

switch:
  - platform: gpio
    name: ${devicename} ${deviceserial} Relay
    pin: GPIO12
    id: relay
  - platform: restart
    name: ${devicename} ${deviceserial} Restart

# Enable time component to reset energy at midnight
time:
  - platform: sntp # could be platform: homeassistant
    timezone: America/Santiago