substitutions:
  devicename: Sonoff POWR2
  deviceserial: 0013903732

esphome:
  name: sonoff-powr2-0013903732

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename} ${deviceserial}
    password: hJ3hJJCSlslr

captive_portal:

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

# Enable ESPHome status output though green LED
status_led:
  pin:
    number: GPIO13
    inverted: True

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${devicename} ${deviceserial} Button
    internal: true
    on_press:
      - switch.toggle: relay

sensor:
  - platform: wifi_signal
    name: ${devicename} ${deviceserial} WiFi Signal
    update_interval: 60s
  - platform: cse7766
    update_interval: 1s
    current:
      name: ${devicename} ${deviceserial} Current
      accuracy_decimals: 5
    voltage:
      name: ${devicename} ${deviceserial} Voltage
    power:
      id: sonoff_power
      name: ${devicename} ${deviceserial} Power
      unit_of_measurement: W
      accuracy_decimals: 2
  - platform: template
    id: sonoff_power_kw
    update_interval: 1s
    name: ${devicename} ${deviceserial} Power (kW)
    unit_of_measurement: kW
    accuracy_decimals: 4
    state_class: measurement
    device_class: power
    lambda: 'return (id(sonoff_power).state / 1000);'
  - platform: total_daily_energy
    name: ${devicename} ${deviceserial} Total Daily Energy
    power_id: sonoff_power_kw

switch:
  - platform: gpio
    name: ${devicename} ${deviceserial} Relay
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON
  - platform: restart
    name: ${devicename} ${deviceserial} Restart

# Enable time component to reset energy at midnight
time:
  - platform: sntp # could be platform: homeassistant
    timezone: America/Santiago