esphome:
  name: sonoff-s26-8377100203

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff S26 8377100203"
    password: "RjtZjZxp7Ml6"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA updates
ota:
  password: !secret ota_password

# Enable ESPHome status output though green LED
status_led:
  pin:
    number: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S26 8377100203 Button"
    on_press:
      - switch.toggle: relay

sensor:
  - platform: wifi_signal
    name: "Sonoff S26 8377100203 WiFi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    name: "Sonoff S26 8377100203 Relay"
    pin: GPIO12
    id: 'relay'
  - platform: restart
    name: "Sonoff S26 8377100203 Restart"
