substitutions:
  id: water-valve
  device_name: Water Valve

esphome:
  name: $id
  friendly_name: $device_name

<<: !include common/board/wemos-d1-mini32.yaml
<<: !include common/common_esp32.yaml

switch:
  - platform: gpio
    pin: 25
    name: "$device_name"
