substitutions:
  id: water-valve
  device_name: Water Valve

esphome:
  name: $id
  friendly_name: $device_name

esp32:
  board: wemos_d1_mini32

<<: !include common/common_esp32.yaml

switch:
  - platform: gpio
    pin: 25
    name: "$device_name"
