esphome:
  name: $id
  friendly_name: "$device_name $device_id"
  on_boot:
    then:
      # read the RTC time once when the system boots
      pcf8563.read_time:

<<: !include ../board/shelly-gen4.yaml
<<: !include ../common-esp32-thread.yaml

external_components:
  - source: github://pr#9248
    components: [ uart ]

status_led:
  pin:
    number: GPIO5
    inverted: true

uart:
  id: uart_bus
  tx_pin: GPIO20
  rx_pin:
    number: GPIO19
    mode: INPUT_PULLUP
  baud_rate: 9600
  stop_bits: 1

i2c:
  sda: GPIO10
  scl: GPIO11

binary_sensor:
  - platform: gpio
    name: $device_name Button
    pin:
      number: GPIO22
      inverted: true
      mode:
        input: true
        pullup: true

time:
  - platform: pcf8563 # Uses AiP8563, a PCF8563 clone
    address: 0x51
    # repeated synchronization is not necessary unless the external RTC
    # is much more accurate than the internal clock
    update_interval: never
  - platform: homeassistant
    # instead try to synchronize via network repeatedly ...
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        pcf8563.write_time:

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    id: temperature
    name: $device_name Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    entity_category: diagnostic
    calibration:
      b_constant: 3350
      reference_resistance: 4.22kOhm
      reference_temperature: 20°C
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 12db

  - platform: bl0942
    uart_id: uart_bus
    update_interval: 1s
    line_frequency: 50Hz
    voltage:
      name: $device_name Voltage
      id: voltage
      entity_category: diagnostic
    current:
      name: $device_name Current
      id: current
    power:
      name: $device_name Power
      id: power
      accuracy_decimals: 2
    energy:
      name: $device_name Energy
      id: energy
      accuracy_decimals: 3
      device_class: energy
      state_class: total_increasing
    frequency:
      name: $device_name Frequency
      id: frequency
      accuracy_decimals: 2
      entity_category: diagnostic
