esphome:
  name: $id
  friendly_name: $device_name $device_id
  platformio_options:
    board_build.flash_mode: dio

<<: !include ../board/espressif-esp32s3.yaml
<<: !include ../common-esp32.yaml
<<: !include ../time/sync.yaml

# SPI for Display
spi:
  - id: display_bus
    mosi_pin: GPIO03
    clk_pin: GPIO05
  - id: rgb_led_bus
    mosi_pin: GPIO40
    clk_pin: GPIO39

font:
  - file: "gfonts://Inconsolata"
    id: inconsolata
    size: 16

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: true
    name: $device_name $device_id Button
    on_press:
      - logger.log: "Button pressed"

light:
  - platform: spi_led_strip
    spi_id: rgb_led_bus
    num_leds: 1
    id: rgb_led
    name: $device_name $device_id RGB LED
    data_rate: 20MHz
    restore_mode: RESTORE_DEFAULT_OFF

display:
  - platform: st7735
    spi_id: display_bus
    model: "INITR_MINI160X80"
    reset_pin: GPIO01
    cs_pin: GPIO04
    dc_pin: GPIO02
    invert_colors: true
    use_bgr: true
    rotation: 270
    device_width: 80
    device_height: 160
    col_start: 26
    row_start: 1
    eight_bit_color: true
    update_interval: 1s
    lambda: |-
      it.printf(3, 30, id(inconsolata), Color(255, 0, 0), id(device_time).now().strftime("%d-%m-%Y %H:%M:%S").c_str());
