esphome:
  name: $id
  friendly_name: "$device_name $device_id"

<<: !include ../board/shelly-gen4.yaml
<<: !include ../common-esp32-thread.yaml

external_components:
  - source: github://pr#9248
    components: [ uart ]

status_led:
  pin:
    number: GPIO5
    inverted: true

uart:
  id: uart_bus
  tx_pin: GPIO20
  rx_pin:
    number: GPIO19
    mode: INPUT_PULLUP
  baud_rate: 9600
  stop_bits: 1

binary_sensor:
  - platform: gpio
    name: $device_name Button
    pin:
      number: GPIO22
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: shelly_1pm_mini_gen4_relay

  - id: shelly_1pm_gen4_switch
    name: $device_name Switch
    platform: gpio
    pin:
      number: GPIO12
    filters:
      - delayed_off: 50ms
    on_press:
      then:
        - switch.toggle: shelly_1pm_mini_gen4_relay

output:
  - id: shelly_1pm_mini_gen4_relay_output
    platform: gpio
    pin: GPIO10

switch:
  - platform: output
    id: shelly_1pm_mini_gen4_relay
    name: "$device_name Relay"
    output: shelly_1pm_mini_gen4_relay_output
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    id: temperature
    name: $device_name Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    entity_category: diagnostic
    calibration:
      b_constant: 3350
      reference_resistance: 4.22kOhm
      reference_temperature: 20°C
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 12db

  - platform: bl0942
    uart_id: uart_bus
    update_interval: 1s
    line_frequency: 50Hz
    voltage:
      name: $device_name Voltage
      id: sensor_voltage
      entity_category: diagnostic
    current:
      name: $device_name Current
      id: sensor_current
    power:
      name: $device_name Power
      id: sensor_power
      accuracy_decimals: 2
    energy:
      name: $device_name Energy
      id: sensor_energy
      accuracy_decimals: 3
      device_class: energy
      state_class: total_increasing
    frequency:
      name: $device_name Frequency
      id: sensor_frequency
      accuracy_decimals: 2
      entity_category: diagnostic
