esphome:
  name: $id
  friendly_name: "$device_name $device_id"
  # comment: $comment
  platformio_options:
    board_build.flash_mode: dio

<<: !include ../board/espressif-esp32c3.yaml
<<: !include ../common-esp32.yaml
<<: !include ../time/sync.yaml

# Enable ESPHome status output though red LED
status_led:
  pin:
    number: GPIO0
    inverted: true

uart:
  id: uart_bus
  tx_pin: GPIO6
  rx_pin: GPIO7
  baud_rate: 9600
  stop_bits: 1

binary_sensor:
  - platform: gpio
    name: $device_name Button
    pin:
      number: GPIO1
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: relay
  - platform: gpio
    name: $device_name Switch
    pin: GPIO10
    on_state:
      then:
        - switch.toggle: relay

switch:
  - platform: gpio
    name: $device_name $device_id Relay
    pin: GPIO5
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: $device_name Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO3
    attenuation: 12db

  - platform: bl0942
    uart_id: uart_bus
    voltage:
      name: $device_name Voltage
    current:
      name: $device_name Current
    power:
      name: $device_name Power
      accuracy_decimals: 2
    energy:
      name: $device_name Energy
      accuracy_decimals: 5
    frequency:
      name: $device_name Frequency
      accuracy_decimals: 2
    update_interval: 1s
